# Generated by Django 2.1.7 on 2019-02-17 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Día de la semana')),
                ('weekday', models.IntegerField(unique=True, verbose_name='Número de dia de la semana (Lunes es 0)')),
            ],
            options={
                'verbose_name': 'Día',
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(unique=True, verbose_name='Hora de la sessión')),
            ],
            options={
                'verbose_name': 'Hora',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisted', models.BooleanField(default=True, verbose_name='Asistencia')),
            ],
            options={
                'verbose_name': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=True, verbose_name='Día')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu.Hour')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu.Day')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu.Hour')),
            ],
            options={
                'verbose_name': 'Plantilla de Sesión',
                'verbose_name_plural': 'Plantillas de Sesión',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wods', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonado',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dejavu.Session'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sessiontemplate',
            unique_together={('day', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('date', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'session')},
        ),
    ]
